# Generated by Django 3.0.3 on 2020-02-23 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
        migrations.CreateModel(
            name='VoteingCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('S', 'Student'), ('SCR', 'Class representative'), ('SPS', 'College president')], max_length=100)),
                ('conductedFor', models.CharField(choices=[('S', 'Student'), ('SCR', 'Class representative'), ('SPS', 'College president')], max_length=100)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('classDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Class')),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('departmentDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('voteForCandidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Candidate')),
                ('votedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('votingCampaign', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.VoteingCampaign')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.Student'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='votingCampaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Elections.VoteingCampaign'),
        ),
    ]
