# Generated by Django 3.0.3 on 2020-02-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0003_auto_20200223_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
