# Generated by Django 3.0.3 on 2020-02-23 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0004_candidate_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='votingCampaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elections.VoteingCampaign'),
        ),
    ]
