# Generated by Django 3.0.3 on 2020-02-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0005_auto_20200223_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='displayImage',
        ),
        migrations.AddField(
            model_name='candidate',
            name='displayImage',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_display_image/'),
        ),
    ]
