# Generated by Django 3.0.3 on 2020-02-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0006_auto_20200223_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name_plural': 'Participating candidates'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student details'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name_plural': 'Voting details'},
        ),
        migrations.AlterModelOptions(
            name='voteingcampaign',
            options={'verbose_name_plural': 'Voting campaign details'},
        ),
        migrations.AddField(
            model_name='voteingcampaign',
            name='nameOfCampaign',
            field=models.CharField(default='_', max_length=200),
        ),
    ]
