# Generated by Django 3.0.3 on 2020-02-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0007_auto_20200223_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='division',
            field=models.CharField(choices=[('MCA1', 'MCA morning'), ('MCA2', 'MCA afternoon'), ('D1', 'D1'), ('D2', 'D2'), ('Some department', 'Some department'), ('EXTC', 'Electronics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('SCR', 'Class representative'), ('SPS', 'College president'), ('Class Representative', 'Class Representative'), ('College president', 'College president')], max_length=100),
        ),
        migrations.AlterField(
            model_name='voteingcampaign',
            name='level',
            field=models.CharField(choices=[('SCR', 'Class representative'), ('SPS', 'College president'), ('Class Representative', 'Class Representative'), ('College president', 'College president')], max_length=100),
        ),
        migrations.AlterField(
            model_name='voteingcampaign',
            name='nameOfCampaign',
            field=models.CharField(default='', max_length=200),
        ),
    ]
