# Generated by Django 3.0.3 on 2020-02-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0008_auto_20200224_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteingcampaign',
            name='shortDescription',
            field=models.CharField(default='', max_length=200),
        ),
    ]
